### ISSUE TITLE
Don't make /g/ the default board

### ISSUE THREAD

**Issue by fuckmobilefags** [Floens/Clover#124]
Dumbshit /b/tards keep posting on /g/ by mistake. Please fix your shitty "app", thank you.

**Comment by Floens** [comment]
I was about to do that. I'm going to randomize the top five boards when Clover is started for the first time.

**Comment by lavsprat** [comment]
Making /b/ the default one would be a better solution. Anyone with half a brain (that is most people who stopped lurking on /b/) will actually switch to the desired board.

**Comment by bakugo** [comment]
Why not just completely remove the default boards and add a board selection screen when the app is first installed? Forcing people into a board by default is pretty pointless.

**Comment by Floens** [comment]
@lavsprat I can't. Google Play doesn't allow nsfw content in their apps. This is why Clover hides all nsfw boards by default.

@bakugo I think it's a better user experience when the user can immediately start browsing 4chan and see all the boards that are available (except nsfw ones), instead of forcing them to add boards immediately. And making such a screen is difficult because the nsfw boards cannot be listed, they need to be added manually by board key.
