### ISSUE TITLE
Request: Browsing native 4chan board archives

### ISSUE THREAD

**Issue by nepflux** [Floens/Clover#173]
Firstly, thanks for your work on this app Floens. I'm getting paid soon so I'll try to shoot a donation your way.

Dashchan already has this feature (browsing / filtering through active 4chan-native board archives), so I imagine it's possible. Access should be somewhere nested in the UI, not in your face, maybe in the three-dotted menu alongside **Catalog options** and **Order** simply as **Archive**.

Some screens of what I'm talking about...

![screen shot 2016-03-14 at 2 59 58 pm](https://cloud.githubusercontent.com/assets/17837288/13761399/9824b7a6-e9f5-11e5-808d-4fcf54538a3a.png)
![screenshot_20160314-150906](https://cloud.githubusercontent.com/assets/17837288/13761590/ca5e8e58-e9f6-11e5-94f6-2ae5fd2ba004.png)
![screenshot_20160314-150231](https://cloud.githubusercontent.com/assets/17837288/13761480/1ed16934-e9f6-11e5-8a90-8e0b4ff872db.png)
![screenshot_20160314-150244](https://cloud.githubusercontent.com/assets/17837288/13761481/205dca72-e9f6-11e5-89d6-49a5407e2fbd.png)

**Comment by Floens** [comment]
The 4chan API does not provide an useful archive feature (it's just a list of id's, no names or anything). As desuwa has said here https://github.com/4chan/4chan-API/issues/36 there's an issue with the file size getting too big. I'm not sure if this has to do with caching or just that it's going to take up too much resources.
So the other option is to parse the html from the archive. This is already on my todo list.
A link to the archive will probably be placed in the drawer, because archive items provide not nearly as much data as normal posts (it's just a subject and reply count) so I don't think it's an appropriate to place in the thread list view.

**Comment by Floens** [comment]
Added in https://github.com/Floens/Clover/commit/9c4f4334f9d009ca4656c1cf2df719b0c5eaf8bc
It loads the html like I said above.
