### ISSUE TITLE
Changing the save location crashes.

### ISSUE THREAD

**Issue by Floens** [Floens/Clover#239]
Changing the save location crashes the app.

Install a fresh copy of Clover, go to the settings and change the save directory to reproduce the issue.

Android version: 7.0
Phone model: Nexus 5X
Clover version: v2.2.0

**Comment by bleakoutside** [comment]
Same for me. Downgrading to the prevous version, changing the save location and then upgrading retains the save location.

Android version 6.0
Phone Moto g 2015
Clover version 2.2.0

**Comment by bleakoutside** [comment]
I was incorrect. I forgot I used a tasker script to automove any files in the directory.

**Comment by bleakoutside** [comment]
My tasker workaround was unnecesary. If you save a pic in the default location you can then change the save directory without a crash. Sorry for spammig your thread floens. Thanks for a great app.

**Comment by Tronmech** [comment]
Missed this one...  It appears that the dialog doesn't let you get out of /SD card (aka /storage/emulated...) to the actual physical SD card.

**Comment by joemck** [comment]
Same here. I installed the app on a new phone (Galaxy S7, Marshmallow). Clicking on change save location crashes the app, seemingly because /storage/emulated/0/Clover doesn't exist. Once I created the folder in a file manager, it now lets me browse for a folder.

I'm still stuck inside device storage and can't browse to my SD, but that's a different ticket.
