### ISSUE TITLE
Images loading slowly

### ISSUE THREAD

**Issue by lmao-emerald** [Floens/Clover#249]
Images loading slowly

Images while navigating a thread load slowly

Open a thread, click an img, swipe to see next img and see it loading slowly

Android version: 6.0.1
Phone model: Nexus 5, Stock ROM
Clover version: Lastest one, problem existed in previous versions as well

**Comment by Floens** [comment]
Images have been loading slowly for me since the beginning of the year, both in the browser and on Clover. Afaik 4chan uses cloudflare in front of their image cdn and it's pretty slow when the image is not on a cf cache server yet and it has to be loaded from 4chan servers. After this initial load the image loads quickly again.
That, and [they have been experimenting with another cdn] or something](https://github.com/Floens/ChanTracking/compare/e14da1b9a7c85cc27ac5d3bcdf9b19461a971484...e6fbf0164702d0996f0c41e124c0375eceb8c55c)
