### ISSUE TITLE
[Suggestion] Preload next/previous image

### ISSUE THREAD

**Issue by denilsonsa** [Floens/Clover#267]
When an image is viewed (zoomed in), Clover could preload the next/previous image. That way, when swiping to view other images, they would be shown instantly, without any delay.

A more aggressive preloading could be to preload everything from the thread, but that's likely to be too much.

Implementing this kind of feature most likely means also adding some options to the Settings screen, to restrict preloading only to Wi-Fi, or disable it entirely. And also deciding if the preloading should also be available to videos.

**Comment by Floens** [comment]
This is a good idea to do again.
Clover v1 preloaded the previous and next image (not on purpose mind you) and I removed that in v2 when the ImageViewerPresenter did all the work.
The image servers are way slower than they used to be, so it's not necessary to focus all the loading on just the middle image; the connection is never saturated that way.
Keep in mind that preloading is something else than displaying the image, due to performance reasons only the middle image is seen in full resolution. We can preload them but there's no reason to render it in high resolution unless it's in the middle.
