### ISSUE TITLE
Request: add back in classic reply window

### ISSUE THREAD

**Issue by ghost** [Floens/Clover#274]
Hello floens,

Would it be possible to add back in the classic reply window from clover 1.X as an option? It was the best one to work with and it was convenient to quickly select multiple anons to reply to without having to also close the reply stub when it popped up after each anon I select to reply to. It was seriously very comfortable and I like that one better over the newer one.

**Comment by Floens** [comment]
What changes do you want to see with the current reply box we have now?
I understand that the reply window is missing some buttons #135 and requests for a bigger box #196 
I don't understand what you mean with " it was convenient to quickly select multiple anons to reply to without having to also close the reply stub when it popped up after each anon I select to reply to." The old screen still required you to close the popup right? Or did the popup not appear at all when quoting someone.

**Comment by samus43** [comment]
Cool to know that the reply window is going to get bigger like how the 1.X reply window was. What I meant by convenient was that I remember for the old 1.X the reply window did not pop up or switch to immediately when you hold down a post and clicked reply to post, you had to manually click the reply button to see the reply window. It made replying to multiple anons take only 2 seconds rather than 10 seconds.

**Comment by Floens** [comment]
The reasoning for removal of the quote option was that it's confusing because it seems like nothing is happening, but we'll look for ways to add it back since it can be handy.
