### ISSUE TITLE
Tapping v1 captcha reloads, sometimes invisible refresh button useless

### ISSUE THREAD

**Issue by ente3000** [Floens/Clover#295]
Tapping the old captcha anywhere refreshes it, even though there's a refresh button at the top. Also, the refresh button sometimes becomes invisible, as both the button and captcha background are white.

That leaves three options:
1. Disable refreshing when the user taps on the captcha itself — Pro: No accidental refreshing — Con: Refresh button still invisible sometimes
2. Remove the button — Pro: No invisible buttons — Con: No obvious refresh buttons
3. Remove the button but add it at some other place, e.g. next to the send icon — Pro: No invisible buttons — Con: Probably ccidental tapping while getting used to it

Yes, I know neither of them are great, but I just wanted to point that out.

Android version: CyanogenOS 13.1.2 based on Android 6.0.1
Phone model: OnePlus One (A0001)
Clover version: 2.2.0

**Comment by Floens** [comment]
Originally the captcha had no refresh button, tapping it would ask the javascript in the webview to reload. The other button was added as a hard reload, it completely reloads the captcha webview.
This is most noticable with captcha v2, because the captcha in it has its own reload button.
Confusing? Maybe. But it was done intentionally.
The invisibility thing is a side effect of the black theme. Not sure how to change that. Other apps would invert the colors, but that's not future proof and we don't actually load an image but a whole webview.

**Comment by Floens** [comment]
captchav1 is now removed, so this issue as become irrelevant.
