### ISSUE TITLE
Location of bookmarks

### ISSUE THREAD

**Issue by Zenostop** [Floens/Clover#311]
I have a ton of threads bookmarked on Clover and I need to reset my phone. However, I can't go to each and every single one and copy the URL. It's just too time-consuming. Are they stored somewhere on the phone where I can just mass-copy them? Or does Clover have some sort of functionality?

**Comment by Floens** [comment]
The bookmarks are stored in the database of Clover, which is a sqlite db with​ a special format.
So, it's not easily exportable, unfortunately.

**Comment by Zenostop** [comment]
Well, I guess you can take this as a feature request then.

**Comment by denilsonsa** [comment]
As a workaround, I have some manual steps to export your bookmarks.

## Part 1: Getting the database file

If your phone is rooted, you can probably get the `ChamDB` from one of the internal `org.floens.chan` folders. Just copy this file to your computer.

Assuming you don't have root on your phone, please make a backup using `adb backup -f backup.ab org.floens.chan` and then extract the `apps/org.floens.chan/db/ChanDB` file. If you are not sure how to do this, please read:

* https://wiki.lineageos.org/adb_fastboot_guide.html
* https://stackoverflow.com/questions/15558353/how-can-one-pull-the-private-data-of-ones-own-android-app
* https://stackoverflow.com/questions/29055634/python-unpack-android-backup
* Or just search on the web.

## Part 2: Reading the database

Pick the tool from your preference that is capable of reading SQLite a database. The command-line `sqlite3` on Debian/Ubuntu works fine, but [you can also try writing some Python code](https://docs.python.org/3.7/library/sqlite3.html).

Type this SQL query:

```sql
SELECT
  loadable.board,
  loadable.no,
  loadable.title,
  pin.thumbnailUrl
FROM
  pin INNER JOIN
  loadable ON pin.loadable_id = loadable.id
ORDER BY pin.`order`;
```

With this, you get the board (the short string of letters), the thread number, the thread name, and the thumbnail. This query doesn't print the full URL of the thread (because it's missing the domain name), but already gives you enough information.

Enjoy!
