### ISSUE TITLE
After the recent crash, new thumbnails don't load

### ISSUE THREAD

**Issue by FoxMcClock** [Floens/Clover#467]
The recent 4chan crash on April 25, 2018 caused thumbnails to not load and instead show an Error message.

Images aren't broken. If you click on a spoilered image and either click on it or scroll to another image they still load. If you click either the back button or click away from the unspoilered image the app softlocks and there is no way to back out. Thumbnails from threads made before the crash still load their thumbnails.

Android version: 7.0
Phone model: Galaxy S7 Edge
Clover version: 2.3.1 F-Droid

**Comment by Rocky6042** [comment]
I'm experiencing a similar issue (didn't make a new post because I figured they might be related). Most OP images as well as thread images, webms and gifs included, don't display and instead have an "Error" message, or, occasionally, they will just 404. Something like 1 in 30 thumbnails display normally for me, but I can't load the images. I haven't had the problem with the app softlocking, and only some of the images from before the crash display properly for me.
Android version: 7.0
Phone: Galaxy S7 SM-G930T
Clover version: 2.3.1

**Comment by Dick-Kickem** [comment]
I'm experiencing the exact same issue.

The last outage before this one caused a similar bug where images wouldn't load, but when I restarted the phone they all loaded. Now that no longer works, restarted twice and still having the problem. Images that were posted prior to the crash still appear but are slow to load. Anything posted post-crash I can't see thumbnails for. I don't get the error or 404, instead I can see the blank space where a thumbnail should be, but clicking it doesn't bring up an image. If I click a pre-crash thumbnail that is visible, I can swipe through and see the images, but if I try to back out of the image the app freezes and has to be closed and re-opened. 

Samsung Galaxy S7 Edge
Clover v2.3.1
Android 7.0

**Comment by devilxking** [comment]
Same issue, on latest Dev build. Android 6.

**Comment by gqo** [comment]
Same behavior. 

Google Pixel XL 1
Clover 2.3.1 F-Droid
Android 8.1.0

**Comment by EfronC** [comment]
Same behavior, on lastest build.

Lenovo Yoga Tablet 2
Clover 2.3.1 F-Droid
Android 4.4

**Comment by dvnger** [comment]
+1 on development build 
Android 8.0
Phone model: Galaxy S7 edge SM-G935W8

**Comment by rxu22** [comment]
Happening on other apps as well, probably due to api calls being shut down or something.

**Comment by Floens** [comment]
The official docs still point to the t. domain. I think it's best to let the 4chan devs have the time to fix this on their side first (the site has been unstable for the past few days) before changing the endpoint on our side.

**Comment by DutyCorp** [comment]
I think one of the problems is for the new image poster after the recent crash, the image doesn't sent to t.4cdn.org as a thumbnail anymore. Instead they are using i.4cdn.org and added s before the file type.

For example,
The filename of the image is 1524730599678.jpg, then the thumbnail is 1524730599678s.jpg

**Comment by Floens** [comment]
Yes, but the official docs still use t.. I've contacted the 4chan devs about this, for now we'll have to wait.
Changing the endpoint hastily to i. without a confirmation might break again at a later time.

**Comment by EfronC** [comment]
I think that the problem that could be solved by the endpoint now, it's the fact that is impossible to open the images if the thumbnail doesn't load. The images are fine, if you open an image that has it's thumbanil working, and then change to the one with the thumbnail broken, the image load and open without problem, but if you open a thread that doesn't have a single thumbnail working, you will not be able to see any image, since you can't "Open one and change to the one that interest you". A good recommendation for the problem now, and if this happened again in the future, is adding an option on the "reply actions"(The 3 points aside any reply) to open the image directly, without clicking the thumbnail. I mean, not saying it's absolutely necessary, but would be an alternative if this happened again while we wait until 4Chan solve their problems.

**Comment by Safrone** [comment]
Having the blank box where the thumbnail should be be clickable might be a good feature to ease current and future thumbnail chicanery

**Comment by tidux** [comment]
If all else fails, allowing the user to set the domain for thumbnails at runtime would be a workaround.

**Comment by dvnger** [comment]
the latest development build reflects this change within the site profile for 4chan. it's posted at https://floens.github.io/Clover/#dev

**Comment by tidux** [comment]
New build installed and working.  Looks like that fixed it.

**Comment by Dick-Kickem** [comment]
Dev build installed, problem solved. Thanks Floens!

**Comment by CCBMhf** [comment]
Newest dev build fixes the issue
Thanks Floens

**Comment by Rocky6042** [comment]
Most recent dev build does in fact fix it. Awesome.

**Comment by chausies** [comment]
Will the updated main build with the fix be sent out anytime soon?

**Comment by Floens** [comment]
https://github.com/4chan/4chan-API/issues/60
I'm going to merge all dev commits into master and create a build now.

**Comment by Floens** [comment]
I'll keep this issue open to avoid people creating new ones.

**Comment by Floens** [comment]
To update:
On Clover/Clover dev: press “Check for updates” in the settings screen to update.
On Clover from F-Droid: wait until F-Droid has processed the update. This can take up to a week. Then the update will appear in F-Droid.

**Comment by anzetal** [comment]
In clover when I checked for updates, it says it's on the latest version. If I manually install the apk, throws an error due to package conflict. I don't want to uninstall and install as there's no backup of filters available

**Comment by Floens** [comment]
Please read the above text. If you downloaded from f-droid, you'll either have to wait, or uninstall it and install my version.

**Comment by bonechene** [comment]
Thanks for the last update. I can play webms without it interrupting my music now.

**Comment by Floens** [comment]
Again for everyone coming from Google, always update your Clover app!
