### ISSUE TITLE
Search no longer stays open when leaving a thread in v3.0.2

### ISSUE THREAD

**Issue by Dashinginthe90s** [Floens/Clover#647]
In version 3.0.1 when searching threads the search results would remain open after backing out of a thread allowing me to continue browsing the results.

In version 3.0.2 backing out of a thread clears the results and clears any text in the search bar. I have to retype my search every time.

In addition tapping search no longer automatically brings up the keyboard. I have to manually tap in the text field to start typing.

**Comment by Adamantcheese** [comment]
For some more detail, pressing back or swiping to the catalog leaves behind a ghost search where the search bar isn't active, but the last search's results stay around and the "Found x" message is there as well.

It appears the new Toolbar system implemented between this version and the last is causing issues. The actual search bar object is destroyed every time and the search query seems to be stored in both ThreadPresenter and the search NavigationItem, but is only ever accessed after immediately being written to. Relevant files seem to be ToolbarPresenter, Toolbar, ToolbarContainer, and ThreadPresenter. I don't know how the UI stack is working here so I can only give that advice for anyone else who tries to fix this.

As for the keyboard thing, it seems that something got lost in the toolbar refactor, as the openKeyboard method in SearchLayout isn't used. Adding in the call to ToolbarContainer's createSearchLayout method solves that problem.

[For reference, this is the diff between versions 3.0.1 and 3.0.2.](https://github.com/Floens/Clover/compare/0cf392d065f69edde4f90ff5081cf82a5e441d82...7cbf5cd2929bac7fa5fe25dc7e7ec81d781cc4f8)

**Comment by FDGRoelofs** [comment]
If you switch to a different board in this state (no search bar visible although results are filtered), the search will be applied without an indicator. This makes it seem that there are fewer or no threads on that board.

**Comment by Adamantcheese** [comment]
I figured it out. Basically, ToolbarPresenter had an extra "search" NavigationItem that was being set/unset when search was opened or closed. Because it was being set to null, the search query held inside it would be deleted, but the actual view would still half stick around. Now the search query is stored in one navigation item, and when search is opened or closed a variable inside it tells the ItemView constructor in ToolbarContainer to create the appropriate View object (Search or Navigation). Because ItemViews are created rather than NavigationItems, everything seems to work correctly.

And yes, that diff I posted above REALLY helped out. It basically was just missed in the conversion to the better system.
