### ISSUE TITLE
Posting broken on 8ch boards that enforce captcha-per-post

### ISSUE THREAD

**Issue by ghost** [Floens/Clover#691]
Clover can no longer post to /tech/ because the BO enabled captcha for all posts. Cover plz fix

**Comment by Adamantcheese** [comment]
Because boards.json doesn't specify if a board has captcha enabled or not, captcha can only be specified to be on for the entire site or off for the entire site. Since it is off for the entire site currently, boards with captcha enabled won't be able to be posted on. If it is turned on, it'll annoy people on other boards who have to now complete a useless captcha. Submit a request for that info to be put somewhere to the admins first.

**Comment by ghost** [comment]
@Adamantcheese You could check if a non-global captcha error is given
